// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP2lx9LsbBKYetmG3AcZTptfX0Go496H8',
    appId: '1:669868430784:web:0894316528d9129b1ce425',
    messagingSenderId: '669868430784',
    projectId: 'deepscan-5617d',
    authDomain: 'deepscan-5617d.firebaseapp.com',
    storageBucket: 'deepscan-5617d.appspot.com',
    measurementId: 'G-6BPDVC7TLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8Lu1XeoYdW5QMNRGXOKTusUgSu-IDcnE',
    appId: '1:669868430784:android:dccfbc4f99cf96881ce425',
    messagingSenderId: '669868430784',
    projectId: 'deepscan-5617d',
    storageBucket: 'deepscan-5617d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGNGHeq-6GXnNfpu0wUEDuDxWYT5Rwi-Q',
    appId: '1:669868430784:ios:4a2d84c0916997601ce425',
    messagingSenderId: '669868430784',
    projectId: 'deepscan-5617d',
    storageBucket: 'deepscan-5617d.appspot.com',
    iosBundleId: 'com.example.deepScan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGNGHeq-6GXnNfpu0wUEDuDxWYT5Rwi-Q',
    appId: '1:669868430784:ios:4a2d84c0916997601ce425',
    messagingSenderId: '669868430784',
    projectId: 'deepscan-5617d',
    storageBucket: 'deepscan-5617d.appspot.com',
    iosBundleId: 'com.example.deepScan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP2lx9LsbBKYetmG3AcZTptfX0Go496H8',
    appId: '1:669868430784:web:a8cc712ea7799bb11ce425',
    messagingSenderId: '669868430784',
    projectId: 'deepscan-5617d',
    authDomain: 'deepscan-5617d.firebaseapp.com',
    storageBucket: 'deepscan-5617d.appspot.com',
    measurementId: 'G-GX61DEJ8NG',
  );
}
